### PR TITLE
Update avr gcc to 8.3.0

### PR DESCRIPTION
**Pull request by zvecr**
TODO:
- [x] verify md5 of downloaded archive

### CODE REVIEW

**Review by yanfali — APPROVED** [review]
LGTM

**Comment by zvecr** [comment]
Doing a little local testing, and adding download verification, seems that `avr-ar` for our chosen archive from zakkemble depends on `libfl2` which depends on the slim 10 update. Otherwise you get the following error:

```console
Archiving: .build/obj_lets_split_rev2_default/quantum/split_common/serial.o                         [ERRORS]
 | 
 | avr-ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
```

**Review by fauxpark — APPROVED** [review]

**Comment by Xelus22** [comment]
Is this stable enough to be merged in now? I'm having trouble upgrading myself within the container.

**Review by drashna — APPROVED** [review]

**Comment by fauxpark** [comment]
Another bump for this. Not quite as useful now that Travis is dead, but still good for people with the Docker setup.

**Comment by filterpaper** [comment]
Bumping this for https://github.com/qmk/qmk_firmware/pull/15971

**Review by tzarc — APPROVED** [review]

**Pull request merged**
