### PR TITLE
Initial TravisCI config

### PR DESCRIPTION
**Pull request by zvecr**
CI will help validate any PR's that are raised against the repo. Preview available at <https://travis-ci.org/zvecr/qmk_base_container/branches>.

For discussion, *What sort of checks can we run during CI to validate the base image is fit for purpose?*

My initial thoughts were to git clone qmk_firmware and build something but that feels a little circular.

### CODE REVIEW

**Review by skullydazed — COMMENTED** [review]
Since I can't add a suggestion to this effect, I'd add something like this:

`  - docker run qmkfm/base_container qmk doctor`

This will mean modifying Dockerfile to add qmk to the pip3 install.

**Comment by skullydazed** [comment]
I opened #5 for the qmk cli support.

**Comment by skullydazed** [comment]
After some testing I think this command works better:

    - docker run qmkfm/base_container qmk setup

As time goes on we can improve the checks that command does. Here's the current output:

```
root@fa2bb39ff282:~# qmk setup
\u2612 qmk_firmware not found!
*** Would you like to clone qmk/qmk_firmware? [y/n] y
Cloning into '/root/qmk_firmware'...
Submodule 'lib/chibios' (https://github.com/qmk/ChibiOS) registered for path 'lib/chibios'
Submodule 'lib/chibios-contrib' (https://github.com/qmk/ChibiOS-Contrib) registered for path 'lib/chibios-contrib'
Submodule 'lib/googletest' (https://github.com/google/googletest) registered for path 'lib/googletest'
Submodule 'lib/ugfx' (https://github.com/qmk/uGFX) registered for path 'lib/ugfx'
Cloning into '/root/qmk_firmware/lib/chibios'...
Cloning into '/root/qmk_firmware/lib/chibios-contrib'...
Cloning into '/root/qmk_firmware/lib/googletest'...
Cloning into '/root/qmk_firmware/lib/ugfx'...
Submodule path 'lib/chibios': checked out '587968d6cbc2b0e1c7147540872f2a67e59ca18b'
Submodule path 'lib/chibios-contrib': checked out 'ede48346eee4b8d6847c19bc01420bee76a5e486'
Submodule path 'lib/googletest': checked out 'ec44c6c1675c25b9827aacd08c02433cccde7780'
Submodule path 'lib/ugfx': checked out '3e97b74e03c93631cdd3ddb2ce43b963fdce19b2'
\u2139 Successfully cloned qmk/qmk_firmware to /root/qmk_firmware!
\u2139 All necessary software is installed.
\u2139 Your build environment is ready!
```

**Comment by zvecr** [comment]
I would personally want to avoid things feeling like they are creating circular dependencies. For instance, the base container doesnt have to hard requirement of having the cli pre installed, as it can be installed on demand. Testing of the cli might want to use the base container, which introduces that nasy circle. That aside I do like the idea of reusing something that already exists, but I think we would want it to exercise the compile environment rather than just git.

For each dependency, the lifetime of its updates partially defines the container behaviour. When the cli changes, which is in another repo, how will this image be rebuilt?

**Comment by skullydazed** [comment]
> For instance, the base container doesnt have to hard requirement of having the cli pre installed, as it can be installed on demand. 

Looking at this issue narrowly I agree. Looking at the larger picture I see more value in knowing the CLI is always available. Right now people primarily interact with QMK via make commands, but interacting via CLI commands is arguably a nicer and easier to learn experience.

> For each dependency, the lifetime of its updates partially defines the container behaviour. When the cli changes, which is in another repo, how will this image be rebuilt?

We can trigger rebuilds of this container when needed. My hope is that the installable CLI mostly doesn't change and that we farm out most commands to the `bin/qmk` inside qmk_firmware.

**Comment by zvecr** [comment]
I still think that qmk/qmk_cli will need its own CI. I would put the case forward that qmk_cli would have its own docker image, and installing it in the base_container make that more difficult. This would potentially be the one that end users interact with and would give a more consistent layering of the stack.

**Comment by zvecr** [comment]
As discussed on Discord, keeping the scope as is for now so it at least flags the build issues in #1.

**Review by skullydazed — APPROVED** [review]

**Pull request merged**
